baseURL = "/"
languageCode = "zh-Hans"
title = "翻译"
theme = "book"
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']

[menu]

[[menu.after]]
  name = "Github"
  url = "https://github.com/mayocream/Translations"
  weight = 2

[[menu.after]]
  name = "About me"
  url = "https://github.com/mayocream"
  weight = 1

[params]
  BookTheme = 'auto'
  BookToC = 'false'
  BookSection = '*'
  BookRepo = 'https://github.com/mayocream/Translations'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/master/webpage'

[markup.goldmark.renderer]
  unsafe = true